title: Artur Pilaszkiewicz Blog
repository: arturpilaszkiewicz/arturpilaszkiewicz.github.io.
description: >- # this means to ignore newlines until "baseurl:"
  blog

theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

google:
 gtag: UA-194258269-1

graphviz:
  options: "-Tsvg" # 'dot' command option
  command: "dot"   # execute this string. specify full path to 'dot' if you need

scholar:
  style: ieee-with-url
  bibliography_list_tag: ul
  relative: "/bibliography.html"